### PR TITLE
Add card addition functionality

### PR DESCRIPTION
**Pull request by joel-oe-lacey**
#### What does this PR do?
This PR adds the ability to create new cards, and add them to the car section dynamically. It achieves this by instantiating a new class of Card on each creation and injecting that to the card section within the HTML.

[TrelloCard/Issue/Story](https://github.com/joel-oe-lacey/IdeaBox/projects/4#card-28203580)

##### Why are we doing this? Any context or related work?
This allows for dynamic functionality on the page with the addition of user information.

#### Where should a reviewer start?
In the ideas.js file.

### CODE REVIEW

**Comment by ghost** [comment]
Just a quick question. Could you explain the 'dateNow' function because I have not seen that before and I'm really confused as to why we are getting the date when creating a unique ID.

**Comment by joel-oe-lacey** [comment]
> Just a quick question. Could you explain the 'dateNow' function because I have not seen that before and I'm really confused as to why we are getting the date when creating a unique ID.

Sure, now is a method on the Date object. It takes the current date and time in milliseconds since a start date in the 70s. As a user can't create two cards at once this will always be unique. Depending on later iterations we might end up having to change this.

Some more details here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now

**Comment by ghost** [comment]
Is that the 1970s or 1870s?

**Comment by joel-oe-lacey** [comment]
> Is that the 1970s or 1870s?

1970s...

**Pull request merged**
